# Change these first
owner: ilhamarrouf # Your GitHub organization or username, where this repository lives
repo: uptime-bukitasam # The name of this repository

sites:
  - name: CISEA
    url: https://cisea.bukitasam.co.id
    expectedStatusCodes:
      - 200
      - 403
  - name: SPEND
    url: https://spend.bukitasam.co.id
    expectedStatusCodes: 
      - 200
      - 403
  - name: BATIC
    url: https://batic.cisea.bukitasam.co.id/app/
  - name: Sentry
    url: https://sentry.bukitasam.co.id
    expectedStatusCodes: 
      - 200
      - 403
  - name: S3
    url: https://s3.bukitasam.co.id
    expectedStatusCodes:
      - 200
      - 403

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bukitasam.co.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/ilhamarrouf/uptime-bukitasam/master/assets/ptba-x.png
  name: Bukit Asam System Status
  introTitle: "**Bukit Asam System Status**"
  introMessage: Bukit Asam provides performance and security to website via its intelligent global network. This is the system status for the Bukit Asam service, both edge network and dashboard/APIs.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
